#!/usr/bin/env bash
# Installs Nginx web server with configure it:
#   Listens on port 80.
#   Returns a page containing "Hello World" when queried
#   at the root with a curl GET request.

apt-get -y update
apt-get -y install nginx
# is used to allow incoming connections to the Nginx HTTP server through the firewall through port 80. using the ufw (Uncomplicated Firewall) command-line tool.
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | /var/www/html/index.nginx-debian.html
service nginx start