#!/usr/bin/env bash
# Installs Nginx web server with configure it:
#   Listens on port 80.
#   Returns a page containing "Hello World" when queried
#   at the root with a curl GET request.

sudo apt-get -y update
sudo apt-get -y install nginx

# is used to allow incoming connections to the Nginx HTTP server through the firewall through port 80. using the ufw (Uncomplicated Firewall) command-line tool.
sudo ufw allow 'Nginx HTTP'

# change the owner of the /var/www directory to the current user recursively. To allow modification of the files in the directory.
sudo chown -R $USER /var/www

# set up a page containing "Hello World" when queried at the root with a curl GET request.
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# restart Nginx to apply the changes
service nginx start