#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
sudo apt-get install -y haproxy

# Configure HAProxy
echo '
frontend http-in
        bind *:80
        mode http
        default_backend web_servers
backend web_servers
        balance roundrobin
        server 151957-web-01 52.72.12.225:80 check
        server 151957-web-02 107.23.106.187:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
