#!/usr/bin/env bash
# enables the default Nginx server block and Kills the process that listens on port 80.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
