#!/bin/bash
ln -s /bin/ls __ls__

# ln: creates a link
# -s: symbolic - creates a symbolic link
# /bin/ls: the file to link to
# __ls__: the name of the symbolic link

# A symbolic link is a file that contains a reference to another file or directory in the form of an absolute or relative path and that affects pathname resolution.