#!/usr/bin/env bash
# Indefinitely writes "I am alive" to the file /tmp/my_process.
#   Pauses two seconds in between each message.

file="/tmp/my_process"

while true; do
  echo "I am alive!" >> "$file"
  sleep 2
done

